name: Deploy Frontend to S3

on:
  push:
    branches:
      - master
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.BURNOOK_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.BURNOOK_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync frontend to S3
      run: aws s3 sync cloud_resume_challenege/chunk1_frontend s3://monvillarin.com --delete
