name: Deploy to AWS S3

on:
  push: 
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.BURNOOK_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BURNOOK_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ vars.MONVILLARIN_COM_NAME }} --delete
        working-directory: chunk1_frontend

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_MONVILLARIN_COM }} --paths "/*"